name: slivers
description: Advanced slivers
version: 0.0.2
homepage: http://github.com/jamesblasco/slivers

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

