name: slivers
description: Advanced slivers
version: 0.0.1
homepage: http://github.com/jamesblasco/slivers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

